const actionsTypes = {
  GET_NEWS_REQUEST: 'GET_NEWS_REQUEST',
  GET_NEWS_ERROR: 'GET_NEWS_ERROR',
  GET_NEWS_RESPONSE: 'GET_NEWS_RESPONSE',
  AUTHORIZATION_REQUEST: 'AUTHORIZATION_REQUEST',
  AUTHORIZATION_REQUEST_ERROR: 'AUTHORIZATION_REQUEST_ERROR',
  AUTHORIZATION_REQUEST_RESPONSE: 'AUTHORIZATION_REQUEST_RESPONSE',
};

export default actionsTypes;
