const actionsTypes = {
  GET_NEWS_REQUEST: 'GET_NEWS_REQUEST',
  GET_NEWS_ERROR: 'GET_NEWS_ERROR',
  GET_NEWS_RESPONSE: 'GET_NEWS_RESPONSE',
  REG_REQUEST: 'REG_REQUEST',
  REG_REQUEST_ERROR: 'REG_REQUEST_ERROR',
  REG_REQUEST_SUCCESS: 'REG_REQUEST_SUCCESS',
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_REQUEST_ERROR: 'AUTH_REQUEST_ERROR',
  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
};

export default actionsTypes;
